TABLE("users")(
	COLUMN("id",        	"INT AUTO_INCREMENT PRIMARY KEY")
	COLUMN("name",      	"VARCHAR(100)")
	COLUMN("email",     	"VARCHAR(255) UNIQUE")
	COLUMN("created_at",	"TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
)
TABLE("products")(
	COLUMN("id",        "INT AUTO_INCREMENT PRIMARY KEY")
	COLUMN("name",      "VARCHAR(32)")
	COLUMN("price",     "INT NOT NULL DEFAULT 500")
	COLUMN("stock",     "INT DEFAULT 10");
)
TABLE("orders")(
	COLUMN("id",         "INT AUTO_INCREMENT PRIMARY KEY")
	COLUMN("user_id",    "INT NOT NULL")
	COLUMN("created_at", "TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
)

